language: php
php:
  - 5.4

before_script:
  - make
  - git clone git://github.com/Leximosi/MPVTester.git ./MPVTester

script:
  - cd ./MPVTester && ./mpvtester.py ./../QuotePostBackLink.zip && cd ..

