language: php
php:
  - 5.4

before_script:
  - git clone git://github.com/Leximosi/MPVTester.git ./MPVTester

script:
  - cd ./MPVTester && ./mpvtester.py ./../install.xml ./../license.txt ./../modx.prosilver.en.xsl ./../root/ && cd ..

