language: php
php:
  - 5.4

before-script:
  - git clone git://github.com/Leximosi/MPVTester.git

script:
  - cd ./MPVTester && ./mpvtester.py ./../install.xml ./../license.txt ./../modx.prosilver.en.xsl ./../root/ && cd ..

